#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: Teza, H.
url: 'http://htunteza.com'

#change it according to your repository name
# disabling since we are using a custom domain
#baseurl: '/online-cv' 

description: Htun Teza is a Burmese Data Scientist, Research Assistant, Dentist, Music, Movie and Anime Enthusiast, currently based in Bangkok Thailand.
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: #3c5560 

# Tracker
analytics: #UA-83979019-1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

name: html to pdf
uses: fifsky/html-to-pdf-action@master
with:
    htmlFile: ./print.html
    outputFile: ./assets/docs/resume.pdf
    pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
